# Generated by Django 4.1.3 on 2022-11-07 21:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tipo_Plato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(blank=True, max_length=200)),
                ('vigencia', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vianda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frecuencia', models.CharField(blank=True, choices=[('Semanal', 'semanal'), ('Quincenal', 'quincenal')], max_length=200)),
                ('tipo_menu', models.CharField(blank=True, choices=[('Normal', 'normal'), ('Diabetico', 'diabetico'), ('Vegetariano', 'vegetariano')], max_length=200)),
                ('fecha_inicio_vianda', models.DateField(blank=True)),
                ('cantidad', models.IntegerField(default=1)),
                ('estado', models.CharField(blank=True, choices=[('Pendiente', 'pendiente'), ('Confirmado', 'confirmado'), ('Cancelado', 'cancelado')], default='Pendiente', max_length=200)),
                ('tipo_platos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vianda.tipo_plato')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
